require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const authRoutes = require('./routes/auth');
const driverRoutes = require('./routes/drivers');
const fineRoutes = require('./routes/fines');
const violationRoutes = require('./routes/violations');
const adminRoutes = require('./routes/admin');

const app = express();
app.use(helmet());
app.use(cors({origin: process.env.FRONTEND_URL || 'http://localhost:3000',credentials: true}));
app.use(express.json());
app.use(express.urlencoded({extended: true}));
app.use('/api/auth', authRoutes);
app.use('/api/drivers', driverRoutes);
app.use('/api/fines', fineRoutes);
app.use('/api/violations', violationRoutes);
app.use('/api/admin', adminRoutes);
app.get('/api/health', (req, res) => {res.json({status: 'OK',timestamp: new Date()})});
app.use((err, req, res, next) => {console.error(err.stack);res.status(500).json({error: 'Internal server error'})});
app.use((req, res) => {res.status(404).json({error: 'Not found'})});
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {console.log(`✅ Server running on port ${PORT}`)});
